#!/usr/bin/env bash

# Set primary prompt styling.
source ~/.bash/git-prompt.sh
export PS1="\[\e[33m\]\u\[\e[m\]: \[\e[32m\]\w\[\e[m\]\[\e[34m\]\$(__git_ps1)\[\e[m\]\n\\$ "

# Set up base16 shell theme.
BASE16_SHELL="$HOME/.config/base16-shell/scripts/base16-tomorrow-night.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

# This is the default path for the go executable.
export PATH="$PATH:/usr/local/go/bin"

export GOPATH="$HOME/dev/go"
export PATH="$GOPATH/bin:$PATH"

# Set Git completion.
source ~/.bash/git-completion.sh

# Aliases.
alias ll='ls -laG --color'

# Set preferred editor.
export VISUAL="vim"
export EDITOR="$VISUAL"
