# Aliases
alias ll='ls -lah'
alias te='open -a TextEdit'
alias chrome='open -a "Google Chrome"'

# Run the zsh built-in function vcs_info to automatically get information from VCSs.
autoload -Uz vcs_info                   # Load version control information
precmd() { vcs_info }
zstyle ':vcs_info:git:*' formats '(%b)' # Format vcs_info_msg_0_ for git

# Set primary prompt styling
setopt prompt_subst # Enable parameter expansion, command substitution and
                    # arithmetic expansion in prompts
export PROMPT=$'\n%B%F{250}%~%f%b %F{2}${vcs_info_msg_0_}%f\n> '
export RPROMPT=""

# Set iTerm2 shortcuts
bindkey "[D" backward-word
bindkey "[C" forward-word
bindkey "^[a" beginning-of-line
bindkey "^[e" end-of-line

# Adjust the time output format
export TIMEFMT=$'\nreal\t%E\nuser\t%U\nsys\t%S'

# Load Git completion
fpath=(~/.zsh $fpath)
autoload -Uz compinit && compinit

# Kubectl completion
source <(kubectl completion zsh)
