set nocompatible
inoremap jk <esc>

filetype off " required by Vundle

" Set the runtime path to include Vundle and initialize.
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Let Vundle manage Vundle, required.
Plugin 'VundleVim/Vundle.vim'

Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'ntpeters/vim-better-whitespace'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'scrooloose/syntastic'
Plugin 'editorconfig/editorconfig-vim'

" All Plugins must be added before the following line.
call vundle#end()         " required by Vundle
filetype plugin indent on " required by Vundle

" Turn on syntax highlights
syntax on

" Reload files changed outside of vim.
set autoread

" Vim command line history.
set history=100

" Show relative line numbers.
set number
set relativenumber

" Start scrolling five lines before the horizontal window border.
set scrolloff=5

" Highlight matching parenthesis.
set showmatch

" Show the filename in the window titlebar.
set title

" Always display the status line.
set laststatus=2

" Copy the indentation from the previous line, when starting a new line.
set autoindent

" Tab to spaces.
" Global settings for all file types but may be overridden in ftplugin.
set tabstop=2
set shiftwidth=2
set expandtab

" Automatically save changes when focus lost.
set autowrite

" Automatically strip trailing whitespace on save.
autocmd BufWritePre <buffer> StripWhitespace

" Change the default mapping and the default command to invoke CtrlP.
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = '0'

" Remap moving across buffers.
nnoremap g] :bn<CR>
nnoremap g[ :bp<CR>

" create :W command, same as :w.
command! -bang -range=% -complete=file -nargs=* W <line1>,<line2>write<bang> <args>

" C++ specific settings.
let g:syntastic_cpp_compiler = 'clang++'
let g:syntastic_cpp_compiler_options = ' -std=c++11 -stdlib=libc++'

" Syntastic settings.
let g:syntastic_check_on_wq = 0

" Make Syntastic passive mode default.
let g:syntastic_mode_map = { 'mode': 'passive', 'active_filetypes': [],'passive_filetypes': [] }

" Turn on syntactic checkers and perform a syntax check.
nnoremap <C-w> :SyntasticCheck<CR> :SyntasticToggleMode<CR>

" Show syntastic errors in the status line.
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

" Allow backspacing over everything in insert mode.
set backspace=indent,eol,start

" Remove extra prefix chars automatically when Shift-J on commented lines
set formatoptions+=j


"" SEARCH """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Highlight all search matches.
set hlsearch

" While searching though a file incrementally highlight matching characters as you type.
set incsearch

" Ignore capital letters during search.
set ignorecase

" Override the ignorecase option if the search pattern contains upper
" case characters. Only used when the search pattern is typed and
" ignorecase option is on.
set smartcase

" Press return to temporarily get out of the highlighted search.
nnoremap <CR> :nohlsearch<CR><CR>


"" AIRLINE PLUGIN """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

let g:airline_theme='minimalist'

" Do not draw separators for empty sections (only for the active window).
let g:airline_skip_empty_sections = 1

" Enable enhanced tabline to show all buffers at the top.
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#show_tab_type = 0

" Customize the bottom-right sections.
let g:airline_section_x = '%l:%c'
let g:airline_section_y = ''
let g:airline_section_z = ''
